ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do

  resources :cats, only: [:index, :show, :create, :new, :update, :edit]

  resources :cat_rental_requests, only: [:show, :new, :create, :index]
end

ninety-nine-cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :datetime         not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#

class Cat < ActiveRecord::Base
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :sex, inclusion: { in: %w(m f), message: "%{value} is not m or f" }

  has_many :cat_rental_requests
end

ninety-nine-cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :datetime         not null
#  end_date   :datetime         not null
#  status     :string           default("PENDING"), not null
#

class CatRentalRequest < ActiveRecord::Base

  # validate :overlapping_requests, ""
  # validate :overlapping_approved_requests, "Cat can't be in more than 1 place at a time"
  belongs_to :cat, :dependent => :destroy

  validate :overlapping

  def overlapping_requests
    # select rows where the requested start and end dates are between start and end dates the table
    CatRentalRequest.select("*").where.not(id: self.id).where("'#{self.start_date}' BETWEEN start_date AND end_date OR '#{self.end_date}' BETWEEN start_date AND end_date")
  end

  def overlapping_approved_requests
    # select approved overlapping requests
    overlapping_requests.select('*').where(status: "APPROVED")
  end

  def overlapping
    self.errors.add(:start_date, message: "Cat can't be in more than 1 place at a time") if overlapping_approved_requests.length > 0
  end
end

ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

ninety-nine-cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @rentals = CatRentalRequest.all
  end

  def show
    @rental = CatRentalRequest.find_by(id: params[:id])
    if @rental
      render :show
    else
      render :index
    end
  end

  def new
    
  end

  def create
    @rental = CatRentalRequest.new(rental_params)
    if @rental.save
      render cat_rental_request_url(@rental)
    else
      redirect_to :new
    end
  end

  private
  def rental_params
    params.require(:rental).permit(:cat_id, :start_date, :end_date)
  end
end

ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    redirect_to action: :index unless @cat
  end

  def new
    @cat = Cat.new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    redirect_to action: :index unless @cat
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def cat_params
    params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
  end
end

ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety-nine-cats/app/views/cat_rental_requests/index.html.erb
<h1>Rental Requests</h1>


<% @rentals.each do |rental| %>
<ul>
  <li> <%= rental.cat_id %> </li>
  <li> <%= rental.start_date %> </li>
  <li> <%= rental.end_date %> </li>
  <li> <%= rental.status %> </li>
</ul>
<% end %>

ninety-nine-cats/app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="post">
  <label for="cat_id">Cat Id:
    <input id="cat_id" type="text" name="rental[cat_id]" value="">
  </label>
  <label for="start_date">Start Date:
    <input id="start_date" type="date" name="rental[start_date]" value="">
  </label>
  <label for="end_date">End Date:
    <input type="date" name="rental[end_date]" value="">
  </label>
  <input type="submit" name="submit" value="Submit">
</form>

ninety-nine-cats/app/views/cats/_form.html.erb
<form action="<%= action_url = action == :new ? cats_url : cat_url(cat) %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name">Name:
    <input type="text" name="cat[name]" value="<%= cat.name %>">
  </label>

  <br>

  <label for="sex">Sex:
    M<input type="radio" name="cat[sex]" <%= cat.sex == "m" ? 'checked="checked"' : "" %> value="m">
    F<input type="radio" name="cat[sex]" <%= cat.sex == "f" ? 'checked="checked"' : "" %> value="f">
  </label>

  <br>

  <label for="color">Color:
    <select name="cat[color]">
      <% if action == :new %>
        <option value="" selected="selected" disabled>Select a color</option>
      <% end %>

      <option <%= cat.color == "blue" ? 'selected="selected"' : "" %> value="blue">blue</option>
      <option <%= cat.color == "red" ? 'selected="selected"' : "" %> value="red">red</option>
      <option <%= cat.color == "green" ? 'selected="selected"' : "" %> value="green">green</option>
      <option <%= cat.color == "tabby" ? 'selected="selected"' : "" %> value="tabby">tabby</option>
      <option <%= cat.color == "invisible" ? 'selected="selected"' : "" %> value="invisible">invisible</option>
    </select>
  </label>

  <br>

  <label for="birth_date">Birth Date:
    <input type="date" name="cat[birth_date]" value="<%= action == :edit ? Date.parse(cat.birth_date.to_s) : "" %>">
  </label>

  <br>

  <label for="description">Description
    <textarea name="cat[description]" rows="8" cols="80"><%= cat.description %></textarea>
  </label>

  <input type="submit" name="submit" value="<%= action == :edit ? "Update" : "Submit" %>">
</form>

ninety-nine-cats/app/views/cats/edit.html.erb
<h2>Build-a-Cat!</h2>
<h3>Make your cat, here:</h3>

<%= render "form", cat: @cat, action: :edit %>

ninety-nine-cats/app/views/cats/index.html.erb
<h1>Cats...</h1>
<ul>
  <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat %></li>
  <% end %>
</ul>

<%= link_to "Add a new cat", new_cat_url %>

ninety-nine-cats/app/views/cats/new.html.erb
<h2>Build-a-Cat!</h2>
<h3>Make your cat, here:</h3>

<%= render "form", cat: @cat, action: :new %>

ninety-nine-cats/app/views/cats/show.html.erb
<h2><%= @cat.name %></h2>
<h3><%= @cat.birth_date.to_s(:db => '%Y-%m-%d') %></h3>
<h3><%= @cat.color %></h3>
<h3><%= @cat.sex %></h3>
<p> <%= @cat.description %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.birth_date.to_s(db: '%Y-%m-%d') %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

ninety-nine-cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>